bindings:
  - name: rabbit.ping
    source:
      kind: messaging.rabbitmq
      properties:
        auto_ack: true
        consumer: kubemq-source
        exclusive: false
        queue: ping
        requeue_on_error: false
        url: amqp://rabbitmq:rabbitmq@35.188.173.255:5672
    target:
      kind: kubemq.events
      properties:
        address: localhost:50000
        channel: events.rabbit.ping
    properties:
      log_level: info
