apiPort: 8081
bindings:
- name: as
  source:
    kind: http
    properties:
      dynamic_mapping: "true"
      methods: get
      path: /*
  target:
    kind: kubemq.events
    properties:
      address: localhost:50000
      dynamic_mapping: "true"
  properties: {}
