bindings:
  - name: api.postgres
    source:
      kind: http
      properties:
        methods: get,post,put
        path: /postgres
    target:
      kind: kubemq.query
      properties:
        address:  localhost:50000
        auth_token: ""
        channel: query.postgres
        timeout_seconds: "60"
    properties: {}
  - name: api.redis
    source:
      kind: http
      properties:
        methods: get,post,put
        path: /redis
    target:
      kind: kubemq.query
      properties:
        address: localhost:50000
        auth_token: ""
        channel: query.redis
        timeout_seconds: "60"
    properties:
      log_level: "debug"
