bindings:
  - name: kubemq-query-azure-eventhubs
    source:
      kind: query
      name: kubemq-query
      properties:
        host: "localhost"
        port: "50000"
        client_id: "kubemq-query-azure-eventhubs-connector"
        auth_token: ""
        channel: "event.azure.eventhubs"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: azure.eventhubs
      name: azure-eventhubs
      properties:
        end_point: "sb://my_account.net"
        shared_access_key_name: "keyname"
        shared_access_key: "213ase123"
        entity_path: "mypath"
        partition_id: "0"