bindings:
  - name: kubemq-query-azure-servicebus
    source:
      kind: query
      name: kubemq-query
      properties:
        host: "localhost"
        port: "50000"
        client_id: "kubemq-query-azure-servicebus-connector"
        auth_token: ""
        channel: "event.azure.servicebus"
        group:   ""
        concurrency: "1"
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: azure.servicebus
      name: azure-servicebus
      properties:
        end_point: "sb://my_account.net"
        shared_access_key_name: "keyname"
        shared_access_key: "213ase123"
        queue: "test"