apiPort: 8080
bindings:
  - name: mqtt-kubemq-event
      kind: messaging.mqtt
      name: mqtt-source
      properties:
        host: "localhost:1883"
        topic: "queue"
        username: "username"
        password: "password"
        client_id: "client_id"
        qos: "0"
    target:
      kind: kubemq.events
      name: target-kubemq-events
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-mqtt-connector"
        channel: "events.mqtt"
    properties:
      log_level: "info"

