bindings:
  - name: activemq
    source:
      kind: messaging.activemq
      properties:
        destination: some-queue
        host: localhost:61613
        password: admin
        username: admin
    target:
      kind: kubemq.events
      properties:
        address: localhost:50000
        auth_token: ""
        channel: event.messaging.activemq
        client_id: test
    properties: {}