bindings:
  - name: kubemq-query-IBM-MQ
    source:
      kind: kubemq.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-IBM-MQ-connector"
        auth_token: ""
        channel: "query.messaging.ibmmq"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: messaging.ibmmq
      name: messaging-ibmmq
      properties:
        queue_manager_name: "QM1"
        host_name: "localhost"
        channel_name: "DEV.APP.SVRCONN"
        username: "app"
        queue_name: "admin"
        password: "passw0rd"
        certificate_label: "NONE"