apiPort: 8080
bindings:
  - name: http-post-kubemq-event
    source:
      kind: source.http
      name: http-post
      properties:
        "methods": "post"
        "path": "/post"
    target:
      kind: target.events
      name: target-kubemq-events
      properties:
        address: "localhost:50000"
        client_id: "kubemq-http-connector"
        auth_token: ""
        channel: "events.post"

