bindings:
  - name: rabbitmq
    source:
      kind: messaging.rabbitmq
      properties:
        auto_ack: "false"
        consumer: "1"
        exclusive: "false"
        queue: some-queue
        requeue_on_error: "false"
        url: amqp://guest:guest@localhost:5672/
    target:
      kind: kubemq.events
      properties:
        address: localhost:50000
        auth_token: ""
        channel: events.messaging.rabbitmq
        client_id: rabbitmq
    properties: {}
