apiPort: 8080
bindings:
  - name: rabbitmq-kubemq-event
    source:
      kind: messaging.rabbitmq
      name: rabbitmq-source
      properties:
        "url": "amqp://guest:guest@localhost:5672/"
        "queue": "queue"
        "consumer": "kubemq"
        "requeue_on_error": "false"
        "auto_ack": "false"
        "exclusive": "false"
    target:
      kind: kubemq.events
      name: target-kubemq-events
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-rabbit-connector"
        channel: "events.rabbitmq"
    properties:
      log_level: "info"

