apiPort: 8080
bindings:
  - name: rabbitmq-kubemq-event
    source:
      kind: source.messaging.rabbitmq
      name: rabbitmq-source
      properties:
        "url": "amqp://rabbitmq:rabbitmq@localhost:5672/"
        "queue": "queue"
        "consumer": "kubemq"
        "requeue_on_error": "false"
        "auto_ack": "false"
        "exclusive": "false"
    target:
      kind: target.events
      name: target-kubemq-events
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-rabbit-connector"
        channel: "events.rabbitmq"
    properties:
      log_level: "info"

